// Shared entry point for desktop AND mobile (iOS/Android) builds.
// Tauri 2 requires a single `run()` fn exported from the lib crate; main.rs
// (desktop bin) and the mobile bindings both call into this.

use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let mut builder = tauri::Builder::default()
        .plugin(tauri_plugin_notification::init())
        .plugin(tauri_plugin_deep_link::init());

    #[cfg(desktop)]
    {
        builder = builder
            .plugin(tauri_plugin_updater::Builder::new().build())
            .plugin(tauri_plugin_single_instance::init(|app, _args, _cwd| {
                // Focus the existing window instead of spawning a second instance.
                if let Some(w) = app.get_webview_window("main") {
                    let _ = w.set_focus();
                }
            }));
    }

    builder
        .setup(|app| {
            use tauri_plugin_deep_link::DeepLinkExt;

            // Register the vantrix:// scheme / https://vantrix.app associated
            // domain at runtime for dev builds (release builds also register
            // via the platform manifest: Info.plist entitlements on iOS,
            // AndroidManifest intent-filter on Android — both generated by
            // `tauri ios/android init` from the `plugins.deep-link` config in
            // tauri.conf.json).
            #[cfg(any(target_os = "android", target_os = "ios"))]
            app.deep_link().register_all()?;

            // The whole app is just a webview pointed at vantrix.app, so
            // "handling" a deep link means navigating the existing window to
            // whatever path was opened — no native routing layer needed.
            // Covers three cases: cold start via link (on_open_url fires
            // once the app + this listener are ready), warm start (app
            // already running, link received while foregrounded), and a
            // notification tap forwarding a ctaUrl through the same scheme
            // (see NATIVE_APP.md — push bridge sends vantrix://<ctaUrl>).
            let handle = app.handle().clone();
            app.deep_link().on_open_url(move |event| {
                let Some(url) = event.urls().first().cloned() else {
                    return;
                };
                let Some(window) = handle.get_webview_window("main") else {
                    return;
                };
                if let Err(err) = window.eval(&format!(
                    "window.location.href = {};",
                    serde_json::to_string(url.as_str()).unwrap()
                )) {
                    eprintln!("deep-link navigation failed for {url}: {err}");
                }
                let _ = window.set_focus();
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running Vantrix");
}
