-- 20261228_character_posts_user_authorship.sql
--
-- Up to now every row in character_posts came from one of two autonomous
-- cron engines (character-feed.ts / character-social-engine.ts) — there was
-- no column recording who (or what) authored a post, because nothing but
-- the AI ever created one.
--
-- This adds real user-authored posts: a premium creator can post as their
-- own character (see /api/characters/:id/posts), and that post is
-- attributed to the human who wrote it, not presented as autonomous
-- character output.
--
--   created_by  — the profile that authored the post. NULL for every
--                 existing (and future AI-generated) row: the cron
--                 engines never pass this column, so its absence itself
--                 means "the character posted this autonomously".
--   author_type — explicit, queryable flag alongside created_by so the
--                 feed/grid UI can render an "posted by {username}" badge
--                 without having to infer authorship from nullability.

ALTER TABLE character_posts
  ADD COLUMN IF NOT EXISTS created_by  UUID REFERENCES profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS author_type TEXT NOT NULL DEFAULT 'ai'
              CHECK (author_type IN ('ai', 'user'));

-- Backfill: every pre-existing row was AI-generated by definition (this
-- migration is the first time a user-authored path exists at all).
UPDATE character_posts SET author_type = 'ai' WHERE created_by IS NULL;

-- Guard against future drift between the two columns at the DB layer,
-- not just app-code discipline: a 'user' post must record who wrote it,
-- and an 'ai' post must not claim a human author.
ALTER TABLE character_posts
  ADD CONSTRAINT character_posts_author_consistency
  CHECK (
    (author_type = 'user' AND created_by IS NOT NULL) OR
    (author_type = 'ai'   AND created_by IS NULL)
  );

CREATE INDEX IF NOT EXISTS idx_character_posts_created_by
  ON character_posts (created_by)
  WHERE created_by IS NOT NULL;
